name: 每日招聘信息推送

on:
  schedule:
    # 使用 UTC 时间，北京时间 12:00 对应 UTC 04:00
    - cron: '0 4 * * *'
    - cron: '0 13 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  run-job-notification:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests schedule
    
    - name: 下载缓存文件
      uses: actions/download-artifact@v4
      with:
        name: job-cache
        path: .
      continue-on-error: true
    
    - name: 运行招聘信息推送脚本
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        OPEN_ID: ${{ secrets.OPEN_ID }}
        JOB_TEMPLATE_ID: ${{ secrets.JOB_TEMPLATE_ID }}
      run: |
        # 创建配置文件
        echo "appID = '${{ secrets.APP_ID }}'" > config.py
        echo "appSecret = '${{ secrets.APP_SECRET }}'" >> config.py
        echo "openId = '${{ secrets.OPEN_ID }}'" >> config.py
        echo "job_template_id = '${{ secrets.JOB_TEMPLATE_ID }}'" >> config.py
        
        # 运行脚本
        python main.py
    
    - name: 上传缓存文件
      uses: actions/upload-artifact@v4
      with:
        name: job-cache
        path: job_cache.json
        retention-days: 7 